### ISSUE TITLE
Rajapinta salasanan palauttamiseksi

### ISSUE THREAD

**Issue by Akzuu** [Tampereen-Urheilusukeltajat/Blenderi-Backend#44]
Rajapinnan käyttäjänä haluan, että

1. Endpoint
- Voin lähettää sähköpostin rajapintaan ja saan 200 vastauksen, löytyi käyttäjää tai ei
- Saan kuitenkin 500 errorin, mikäli käyttäjä löytyy JA sähköpostin lähettäminen epäonnistuu (esim SendGrid hylkää pyynnön)
- Ylempi periaatteessa mahdollistaa rekistöröityneiden käyttäjien metsästämisen, mutta niitä voi metsästää myös rekistöröitymisellä, jos vain tietää sähköpostin
- Rajapinta luo oikein toimiessaan JWT tokenin ja lähettää tämän tokenin clickattavan linkin queryParametrina käyttäjän sähköpostiin

2. Endpoint
- Voin lähettää käyttäjän saaman salaisen JWT tokenin sekä uuden salasanan kahdesti rajapintaan
- Rajapinta tarkistaa JWT:n ja mikäli se on ok, vaihtaa käyttäjän salasanan
- Rajapinta palauttaa 200 OK tai 500 ISE virheellisessä tilanteessa

**Comment by Akzuu** [comment]
![Image](https://user-images.githubusercontent.com/33838340/207306712-20b72f62-0ac2-4e2d-8309-dcaa583b5fe2.png)

**Comment by ilesoft** [comment]
## pohdintoja muualta

Meidän pitää rajoittaa käyttäjälle lähtevien sähköpostien määrää tilanteessa, jossa joku pahanilkinen osapuoli tekee 1000000 kpl salasanaresetpyyntöjä uhrin sähköpostiosoitteella.

Mut sit kun ottaa huomioon millainen media sähköposti on niin ei sitä voi oikein yhteenkään kappaleeseen rajoittaa

Onko olemassa standardia linkin voimassaoloaikaa?

Ekana tuli mieleen, että sallittais ~5 voimassa olevaa tokenia (=max ~5 sähköpostia per tokenin voimassaoloaika tms.) ja loput resetpyynnöt menis suoraan roskiin

Voimassa olevien tokenien tallentamiseen tullaan käyttämään redisiä kun se kerron jo löytyy teknologiapinosta. Ja se että tokenit katoaa mahdollisen uudelleenkäynnistyksen yhteydessä ei pitäisi olla ongelma.

**Comment by ilesoft** [comment]
# Tokenien tallentaminen redisiin
Tokenit tallennetaan käyttäjäkohtaisena SET-tietorakenteena, jonka kokoa rajoitetaan ohjelmallisesti (noin) viiteen tokeniin. Setille asetetaan vanhenemisaika ensimmäisen jäsenen lisäämisen yhteydessä.

**Comment by ilesoft** [comment]
Salasanan nollaus -endpointissa olis hyvä olla joku rate limitteri

**Comment by ilesoft** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html
